# Generated by Django 5.0.7 on 2024-07-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
    ]
